### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by swetlasg** [Stremio/stremio-icons#1]
1. ~~chevron up icon~~
2. ~~chevron right icon~~
3. ~~icon for video component when poster is not found~~

**Comment by NikolaBorislavovHristov** [comment]
4. ic_play_curriculum_centered

**Comment by NikolaBorislavovHristov** [comment]
5. circle

**Comment by NikolaBorislavovHristov** [comment]
6. icon for types other than movie, series, channel, tv

**Comment by NikolaBorislavovHristov** [comment]
7. ic_arrow_thin_down
8. ic_arrow_thin_up

**Comment by Ivshti** [comment]
those seem to be ready.. or not?

**Comment by nklhrstv** [comment]
info icon 
videos icon

**Comment by nklhrstv** [comment]
prev/next video
