### ISSUE TITLE
Icon for anime type

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-icons#10]
Add an icon for `anime` type catalogs/metas.

**Comment by alesinka** [comment]
Added the following icon for anime catalogs in the icon pack (attached latest):
<img width="153" alt="image" src="https://github.com/Stremio/stremio-icons/assets/24762344/b69ffff6-4a71-4cec-ba1c-ede0295540bc">

![stremio-icons](https://github.com/Stremio/stremio-icons/assets/24762344/555af67a-88ae-4557-bddd-56598cafad06)

**Comment by jaruba** [comment]
Added with this PR: https://github.com/Stremio/stremio-icons/pull/14
